<?php

namespace Tests\Feature;

use App\Thread;
use Tests\TestCase;
//use Illuminate\Foundation\Testing\DatabaseMigrations;


class ReadThreadsTest extends TestCase
{
    private $thread;
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread=$this->create(Thread::class);
    }
    
    /**
     * 用户能浏览文章
     * @test
     * @return void
     */
    public function a_user_can_brower_all_threads()
    {
        $response = $this->get('/threads');
        $response->assertSee($this->thread->title);
    }
    
    /**
     * @test
     */
    public function a_user_can_brower_single_file()
    {
        $response=$this->get($this->thread->path());
        $response->assertSee($this->thread->title);
    }
    
    /**
     * @test
     */
    public function a_user_can_read_replies_that_are_associated_with_a_thread()
    {
        // 如果存在 Thread
        // 并且该 Thread 拥有回复
        // 那么当我们看该 Thread 时
        // 我们也要看到回复
        $reply=factory('App\Reply')->create(
            ['thread_id'=>$this->thread->id]
        );
        $response=$this->get($this->thread->path());
        $response->assertSee($reply->body);
    }
}
